server:
  servlet:
    context-path: /upay


spring:
    datasource:
        name: upay
        url: jdbc:mysql://xx.xx.xx.244:3306/upay?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        password: 'xxxxxxxxxx'
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 6000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
 




mybatis:
  mapper-locations: classpath:mapping/*.xml     #mapper文件路径
  type-aliases-package: com.mb.upay.model   #实体类的包路径
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check


#redis配置
redis:
  host: xxxxxxxx
  port: 6379
  timeout: 3
  password: xxxxxx
  poolMaxTotal: 20
  poolMaxIdle: 10
  poolMaxWait: 3


